export const staticContents = [
  {
    "id": 1,
    "title": "Eros donec ac odio tempor orci dapibus ultrices",
    "author": "Lorem",
    "content": "Elementum nisi quis eleifend quam. Mi quis hendrerit dolor magna eget est lorem ipsum. Imperdiet sed euismod nisi porta lorem. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Aliquam sem et tortor consequat id porta nibh venenatis. Laoreet suspendisse interdum consectetur libero. Eget arcu dictum varius duis at consectetur. Id cursus metus aliquam eleifend. Molestie a iaculis at erat pellentesque adipiscing commodo. Sed risus pretium quam vulputate dignissim suspendisse in. Nunc pulvinar sapien et ligula ullamcorper malesuada. Arcu ac tortor dignissim convallis aenean et tortor at. Mauris rhoncus aenean vel elit scelerisque. Eget gravida cum sociis natoque penatibus et magnis dis parturient. At varius vel pharetra vel turpis. Pulvinar neque laoreet suspendisse interdum consectetur. Convallis tellus id interdum velit laoreet id.",
    "postDate": "1-1-2023",
  },
  {
    "id": 2,
    "title": "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    "author": "ipsum",
    "content": "Arcu non odio euismod lacinia at quis risus sed vulputate. In hac habitasse platea dictumst quisque. Cras ornare arcu dui vivamus arcu. Id venenatis a condimentum vitae. Ut tortor pretium viverra suspendisse potenti nullam ac. Vitae elementum curabitur vitae nunc. Eget sit amet tellus cras. Laoreet suspendisse interdum consectetur libero id. Odio euismod lacinia at quis. Et netus et malesuada fames ac turpis egestas sed tempus. Consectetur lorem donec massa sapien faucibus et. Turpis egestas sed tempus urna et. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Justo eget magna fermentum iaculis eu non diam phasellus. Et netus et malesuada fames ac turpis egestas.",
    "postDate": "2-1-2023",
  },
  {
    "id": 3,
    "title": "Cum sociis natoque penatibus et magnis dis parturient montes nascetur",
    "author": "Lorem",
    "content": "Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Sit amet nisl suscipit adipiscing bibendum. Tincidunt nunc pulvinar sapien et. Amet tellus cras adipiscing enim eu turpis. Magnis dis parturient montes nascetur ridiculus mus mauris. Morbi tempus iaculis urna id. Facilisis volutpat est velit egestas dui. Vel elit scelerisque mauris pellentesque. Duis ultricies lacus sed turpis tincidunt id aliquet. Odio pellentesque diam volutpat commodo. Mauris sit amet massa vitae. Donec massa sapien faucibus et molestie ac feugiat sed lectus. Elementum nisi quis eleifend quam adipiscing vitae. Diam sit amet nisl suscipit. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Diam sollicitudin tempor id eu nisl nunc mi. Ornare suspendisse sed nisi lacus sed. Ut etiam sit amet nisl purus.",
    "postDate": "3-1-2023",
  },
  {
    "id": 4,
    "title": "Tellus cras adipiscing enim eu turpis",
    "author": "ipsum",
    "content": "Cursus in hac habitasse platea dictumst quisque sagittis. Dui ut ornare lectus sit amet est. Adipiscing tristique risus nec feugiat in. Turpis massa sed elementum tempus egestas sed sed risus pretium. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Mauris pharetra et ultrices neque ornare aenean euismod elementum. Dapibus ultrices in iaculis nunc. Adipiscing tristique risus nec feugiat in. Ultricies lacus sed turpis tincidunt id. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Vitae semper quis lectus nulla.",
    "postDate": "4-1-2023",
  },
  {
    "id": 5,
    "title": "Ut pharetra sit amet aliquam",
    "author": "Lorem",
    "content": "Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Odio aenean sed adipiscing diam donec. Suspendisse faucibus interdum posuere lorem. Cursus euismod quis viverra nibh cras. Tellus id interdum velit laoreet. Urna nec tincidunt praesent semper feugiat nibh sed. Phasellus vestibulum lorem sed risus ultricies tristique. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Facilisis mauris sit amet massa vitae tortor condimentum. Ut tortor pretium viverra suspendisse potenti nullam. Arcu ac tortor dignissim convallis aenean et tortor at risus. Odio euismod lacinia at quis. Non blandit massa enim nec dui nunc mattis enim ut.",
    "postDate": "5-1-2023",
  },
  {
    "id": 6,
    "title": "Lacinia at quis risus sed vulputate",
    "author": "Lorem",
    "content": "Neque egestas congue quisque egestas diam in arcu. Lacus vel facilisis volutpat est velit. Eget nullam non nisi est sit. Nulla at volutpat diam ut venenatis tellus in. Sem nulla pharetra diam sit amet nisl. Enim praesent elementum facilisis leo vel. Tempor id eu nisl nunc. Mauris vitae ultricies leo integer malesuada nunc vel. Ac turpis egestas sed tempus urna et pharetra pharetra massa. Magna eget est lorem ipsum dolor sit. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Sit amet purus gravida quis blandit. Mattis nunc sed blandit libero. Enim sit amet venenatis urna.",
    "postDate": "6-1-2023",
  },
  {
    "id": 7,
    "title": "Interdum posuere lorem ipsum dolor sit. Non consectetur a erat nam",
    "author": "ipsum",
    "content": "Odio morbi quis commodo odio aenean sed. Quis lectus nulla at volutpat diam. Amet consectetur adipiscing elit pellentesque habitant morbi. Amet risus nullam eget felis. Ornare massa eget egestas purus viverra. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Eget duis at tellus at urna. Amet volutpat consequat mauris nunc. Nibh nisl condimentum id venenatis a condimentum. Quisque id diam vel quam elementum pulvinar etiam non quam. Et netus et malesuada fames ac turpis egestas. Mauris a diam maecenas sed enim ut sem viverra aliquet. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Laoreet id donec ultrices tincidunt arcu non sodales. Velit dignissim sodales ut eu sem integer vitae justo eget.",
    "postDate": "7-1-2023",
  },
  {
    "id": 8,
    "title": "Sed arcu non odio euismod lacinia at quis risus sed. Elementum nibh tellus molestie nunc non blandit massa",
    "author": "Lorem",
    "content": "Vitae nunc sed velit dignissim sodales. Pellentesque nec nam aliquam sem et tortor. Leo a diam sollicitudin tempor id eu nisl nunc. Urna id volutpat lacus laoreet non. Risus feugiat in ante metus dictum at tempor. Mauris nunc congue nisi vitae suscipit. Mattis enim ut tellus elementum sagittis vitae. Tellus pellentesque eu tincidunt tortor. Enim tortor at auctor urna. Neque vitae tempus quam pellentesque nec nam aliquam sem et. Quis hendrerit dolor magna eget est lorem ipsum dolor.",
    "postDate": "8-1-2023",
  },
  {
    "id": 9,
    "title": "Viverra suspendisse potenti nullam ac tortor.",
    "author": "ipsum",
    "content": "Eget arcu dictum varius duis at consectetur lorem donec massa. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Feugiat pretium nibh ipsum consequat nisl vel. In iaculis nunc sed augue lacus viverra vitae congue. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Mi quis hendrerit dolor magna eget est. Congue mauris rhoncus aenean vel elit. Tincidunt arcu non sodales neque. Odio facilisis mauris sit amet massa vitae tortor. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Tellus integer feugiat scelerisque varius morbi. Urna id volutpat lacus laoreet non. Sit amet mauris commodo quis imperdiet massa. Egestas dui id ornare arcu odio ut sem. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis.",
    "postDate": "9-1-2023",
  },
  {
    "id": 10,
    "title": "Aliquam ultrices sagittis orci a scelerisque purus semper eget duis",
    "author": "ipsum",
    "content": "Sit amet est placerat in egestas erat imperdiet. Diam volutpat commodo sed egestas egestas fringilla phasellus. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Dapibus ultrices in iaculis nunc sed. Hendrerit gravida rutrum quisque non tellus. Ultricies integer quis auctor elit sed vulputate mi sit amet. Convallis tellus id interdum velit laoreet. Etiam erat velit scelerisque in dictum non consectetur. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium. Vel risus commodo viverra maecenas accumsan lacus.",
    "postDate": "10-1-2023",
  },
]